# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

version: "2.3"

services:
  # ROS Foxy navigation
  nav2:
    image: husarion/nav2:galactic-latest
    restart: unless-stopped
    network_mode: host
    ipc: host
    environment:
      - ROS_DOMAIN_ID=2
    command: ros2 launch husarion_nav2 bringup_both.launch.py

  rviz:
    image: husarion/rviz2
    restart: unless-stopped
    network_mode: host
    ipc: host
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=2
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./rosbot_pro.rviz:/root/.rviz2/default.rviz