version: "2.3"

services:
  # ROS Foxy navigation
  nav2:
    image: husarion/nav2:galactic-latest
    tty: true
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - "ROS_DOMAIN_ID=0"
    command: ros2 launch husarion_nav2 bringup_both.launch.py


  # ROS Foxy Rviz2 VNC
  rviz2:
    image: husarion/ros2-desktop-vnc:latest
    network_mode: host
    volumes:
      - ./rosbot_pro.rviz:/root/.rviz2/default.rviz
    ports: 
      - 6080:80
    shm_size: '512m'