# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.ddsrouter.rosbot.yaml up

version: "2.3"

services:

  # ROS Galactic navigation 2
  nav2:
    image: husarion/nav2:galactic-latest
    restart: on-failure
    command: ros2 launch husarion_nav2 bringup_both.launch.py

  # ROS Noetic + ROS 2 Galactic
  bridge:
    image: ros:galactic-ros1-bridge
    restart: on-failure
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    command: ros2 run ros1_bridge dynamic_bridge

  # ROS Master (using custom port in case Master is already running on host OS)
  ros-master:
    image: ros:melodic-ros-core
    restart: on-failure
    command: stdbuf -o L roscore

  # ROS Melodic rosbot hardware layer
  rosbot:
    image: husarion/rosbot   
    restart: on-failure
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - SERIAL_PORT=/dev/ttyS4 # default: ttyS1 - rosbot2.0; ttyS4 - rosbot2.0 `pro
    devices:
      - /dev/ttyS4   # must match environment SERIAL_PORT 
    command: roslaunch --wait rosbot_description rosbot_docker.launch
    
  # ROS Melodic Rplidar
  rplidar:
    image: husarion/rplidar:latest
    restart: on-failure
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    devices:
      - /dev/ttyUSB0
    command: roslaunch --wait rplidar_ros rplidar_a3.launch # For Rosbot 2.0 PRO use roslaunch rplidar_ros rplidar_a3.launch

  dds_router:
    image: ghcr.io/dominikn/ros-galactic-fastdds:latest
    restart: always
    network_mode: service:husarnet
    volumes:
      - ./router-config.rosbot.yaml:/config.yaml
    command: bash -c "ddsrouter -c /config.yaml -r 10"

  husarnet:
    image: husarnet/husarnet
    restart: on-failure
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosbot
      - JOINCODE=${HUSARNET_JOINCODE}