# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml -f compose.pc.ddsrouter.yaml up

version: "2.3"

services:

  listener:
    build: .
    command: ros2 run demo_nodes_cpp listener

  dds-router-pc:
    image: husarnet/dds-router
    restart: always
    network_mode: service:husarnet-pc
    environment:
      - DS_HOSTNAME=rosbot
    volumes:
      - ./router-config.pc.yaml:/config.yaml
    command: bash -c "/wait_ds.sh && ddsrouter -c /config.yaml -r 10"

  husarnet-pc:
    image: husarnet/husarnet
    restart: on-failure
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rviz
      - JOINCODE=${HUSARNET_JOINCODE}

# # Needed if running all compose.*.yaml files on the same host. Thanks to those lines a new subnet for this compose file is created
# networks:
#   default:
#     name: net_pc
#     driver: bridge