allowlist:
  - name: "rt/odom"
    type: "nav_msgs::msg::dds_::Odometry_"
  - name: "rt/rosout"
    type: "rcl_interfaces::msg::dds_::Log_"
  - name: "rt/scan"
    type: "sensor_msgs::msg::dds_::LaserScan_"
  - name: "rt/tf"
    type: "tf2_msgs::msg::dds_::TFMessage_"
  - name: "rt/chatter1"
    type: "std_msgs::msg::dds_::String_"
    
internal_partipant:
  type: local
  domain: 0

external_partipant:
  type: "local-discovery-server"
  id: 200

  listening-addresses:
    - domain: "rosbot"  # using hostname instead of Husarnet IPv6 addr
      port: 11811
      transport: "udp"
      
