# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml -f compose.pc.ddsrouter.yaml up

version: "2.3"

services:

  dds_router:
    image: ghcr.io/dominikn/ros-galactic-fastdds:latest
    restart: always
    network_mode: service:husarnet
    volumes:
      - ./router-config.pc.yaml:/config.yaml
    command: bash -c "ddsrouter -c /config.yaml -r 10"

  husarnet:
    image: husarnet/husarnet
    restart: on-failure
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rviz
      - JOINCODE=${HUSARNET_JOINCODE}
