# Quick Start
# $ docker compose -f compose.rosbot.yaml up

version: "2.3"

services:

  rplidar:
    image: husarion/rplidar:galactic
    restart: unless-stopped
    network_mode: service:husarnet
    devices:
      - /dev/ttyUSB0
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds-config.xml

    command: ros2 launch rplidar_ros2 rplidar_a3_launch.py

  nav2:
    image: husarion/nav2:galactic
    restart: unless-stopped
    network_mode: service:husarnet
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds-config.xml
    command: ros2 launch husarion_nav2 bringup_both.launch.py

  # ROS Noetic + ROS 2 Galactic
  bridge:
    image: ros:galactic-ros1-bridge
    restart: unless-stopped
    network_mode: service:husarnet
    volumes:
      - ./dds-config.xml:/dds-config.xml 
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds-config.xml
      - ROS_MASTER_URI=http://ros-master:11311
    command: ros2 run ros1_bridge dynamic_bridge

  # ROS Master (using custom port in case Master is already running on host OS)
  ros-master:
    image: ros:melodic-ros-core
    restart: unless-stopped
    command: stdbuf -o L roscore

  # ROS Melodic rosbot hardware layer
  rosbot:
    image: husarion/rosbot   
    restart: unless-stopped
    devices:
      - /dev/ttyS4   # must match environment SERIAL_PORT 
    environment:
      - SERIAL_PORT=/dev/ttyS4 # default: ttyS1 - rosbot2.0; ttyS4 - rosbot2.0 `pro
      - ROS_MASTER_URI=http://ros-master:11311
    command: roslaunch --wait rosbot_description rosbot_docker.launch
    
  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosbot
      - JOINCODE=${HUSARNET_JOINCODE}
